version: '3.7'

services:
  app:
    image: node:16-alpine
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./.data/redis:/data
